export const VisibilityFilters = {
    SHOW_ALL: 'SHOW_ALL_TODO',
    SHOW_COMPLETED: 'SHOW_COMPLETED_TODO',
    SHOW_ACTIVE: 'SHOW_ACTIVE_TODO'
}

export const TOGGLE_TODO = 'TOGGLE_TODO'

export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'

export const ADD_TODO = 'ADD_TODO'
