export const VisibilityFilters = {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_COMPLETED: 'SHOW_COMPLETED',
    SHOW_ACTIVE: 'SHOW_ACTIVE'
}

export const TODOLIST_SET_VISIBILITY_FILTER = 'TODOLIST_SET_VISIBILITY_FILTER'
